name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build cuda11.8.0-ubuntu22.04-oneclick --file Dockerfile --tag yvonne-llm:$(date +%s)
